### ISSUE TITLE
Rethink hardcoded checking alert types

### ISSUE THREAD

**Issue by C-Lodder** [toiletKit/custom-elements#19]
https://github.com/toiletKit/custom-elements/blob/master/src/js/alert/alert.js#L61

**Comment by KarlyGrCm** [comment]
Let me understand. Is this what you want to chance?
```
if (!newValue || ['info', 'primary', 'warning', 'success', 'danger'].indexOf(newValue) === -1) {
    this.type = 'info';
}
```

**Comment by C-Lodder** [comment]
Hi @KarlyGrCm - Yes that's correct.

The different colour variations are defined in here:

https://github.com/toiletKit/custom-elements/blob/master/src/scss/_variables.scss#L39

So if users add their own colour, then the following will not work:

```
if (!newValue || ['info', 'primary', 'warning', 'success', 'danger'].indexOf(newValue) === -1) {
    this.type = 'info';
}
```

We also need to bare in mind that users can extend the `$theme-colors()` array for a specific custom element, like we're currently doing for alerts: https://github.com/toiletKit/custom-elements/blob/master/src/scss/alert/alert.scss#L7

**Comment by C-Lodder** [comment]
@dgt41 - can we not get away with just using this?
```
if (!newValue) {
          this.type = 'info';
}
```

**Comment by dgt41** [comment]
Probably with one more check that the attribute is string. But we are already shipping 5 different colors/schemes so is this really needed?

**Comment by C-Lodder** [comment]
I dont it's needed to be honest. It's also just problematic if users extend the colour array.

**Comment by C-Lodder** [comment]
PR: https://github.com/toiletKit/custom-elements/pull/33
