### ISSUE TITLE
Fix the sauce labs no session thing

### ISSUE THREAD

**Issue by C-Lodder** [toiletKit/custom-elements#7]
![30158329-98d2d5a6-93cd-11e7-8e33-ce3f1d37febc](https://user-images.githubusercontent.com/2019801/30249937-3ac6cb5c-963e-11e7-8bed-f5d648f4e806.png)

**Comment by dgt41** [comment]
Fixed 
![screen shot 2017-09-10 at 21 01 12](https://user-images.githubusercontent.com/3889375/30251585-3f3907b8-966b-11e7-8bbd-a043f5d3eea3.png)
